#!/bin/sh
prevdir=`pwd`
ocamltterhome=`dirname $0`
cd $ocamltterhome

with_pkgs=""
for pkg in cryptokit tiny_json tiny_json_conv ocaml_conv meta_conv spotlib curl
do
  with_pkgs="$with_pkgs -I `ocamlfind query $pkg`"
done

if [ -f ocamltter.ml ]; then
  # We are at the source dir
  incl="$with_pkgs -I +threads -I ../lib"
  initfile='./ocamlinit.ml'
else
  # We are not at the source dir. omake install has been done.
  for pkg in twitter ocamltter
  do
    with_pkgs="$with_pkgs -I `ocamlfind query $pkg`"
  done
  incl="$with_pkgs"
  initfile=`ocamlfind query ocamltter`/ocamlinit.ml
fi

# override initfile if we have $1
if [ $# -ne 1 ]; then
    : 
else
    initfile=$1
fi
# echo ./ocamltter_top $incl -init $initfile
./ocamltter_top $incl -init $initfile
cd $prevdir
