#!/bin/sh
prevdir=`pwd`
ocamltterhome=`dirname $0`
cd $ocamltterhome
mkdir -p doc
ocamlfind ocamldoc -I lib -I lib/base -I lib/twitter -I toplevel -thread \
    -package cryptokit,spotlib,tiny_json_conv,tiny_json,ocaml_conv \
    -syntax camlp4o -package meta_conv.syntax -html -d doc \
    lib/base/util.mli \
    lib/base/llist.mli \
    lib/base/utf16.mli \
    lib/base/parserMonad.mli \
    lib/base/base64.mli \
    lib/base/xml.mli \
    lib/base/http.mli \
    lib/base/oauth.mli \
    lib/base/googleTTS.mli \
    lib/twitter/auth.mli \
    lib/twitter/api_intf.ml \
    lib/twitter/api11.ml \
    toplevel/oConfig.ml \
    toplevel/ocamltter.mli \
    toplevel/ocamlinit.ml
cd $prevdir
